#baseurl: "/bootstrap-material-design"
#url: "http://fezvrasta.github.io"
#url: "http://rosskevin.github.io"

include:
  - .nojekyll


sass:
    sass_dir: sass

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              http://fezvrasta.github.io/bootstrap-material-design
encoding:         UTF-8

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  4.0.0-alpha
repo:             https://github.com/fezvrasta/bootstrap-material-design

download:
  source:         https://github.com/fezvrasta/bootstrap-material-design/archive/v0.4.1.zip
  dist:           https://github.com/fezvrasta/bootstrap-material-design/releases/download/v0.4.1/bootstrap-0.4.1-dist.zip

#blog:             http://blog.getbootstrap.com
#expo:             http://expo.getbootstrap.com
#themes:           http://themes.getbootstrap.com

#
cdn:
#  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/v4-dev/dist/css/bootstrap-material-design.css
#  css_hash:       "sha384-XXXXXXXX"
  js:             https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/v4-dev/dist/js/bootstrap-material-design.js
#  js_hash:        "sha384-XXXXXXXX"
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
